# Generated by Django 5.2.4 on 2025-07-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
