# Generated by Django 5.2.4 on 2025-07-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_chat_messages_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
