# Generated by Django 5.2.4 on 2025-07-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_monthly_chat_messages_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_medication_questions_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
