# Generated by Django 5.2.4 on 2025-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_monthly_medication_questions_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_mentalhealth_messages_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
